
package UI;
import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import validation.Formatter;
import validation.Validator;
import logic.*;


//import resources.*;

/**
 *
 * @author KevinChen
 */
public class CarSaleMainUI extends javax.swing.JFrame {

     private Scanner s, sc;
     String filedIdentifer = "Chevorlate2015SaleApp";
     
     DateFormat df = new SimpleDateFormat ("yyyy/MM/dd/hh/mm/ss");
     Date date = new Date();
    String nl = System.getProperty("line.separator");
    final private String [] checkButArray = new String[9];
    
    final JFileChooser fc = new JFileChooser();//Created JFileChooser Object 
     File f = null;
     
     

     
     
     
     
     
     
    /**
     * Creates new form CarSaleMain
     */
    public CarSaleMainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butGroupCar = new javax.swing.ButtonGroup();
        lblBkPic5 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        panelVehicle = new javax.swing.JPanel();
        radButCruze = new javax.swing.JRadioButton();
        radButEquinox = new javax.swing.JRadioButton();
        radButVolt = new javax.swing.JRadioButton();
        radBut1 = new javax.swing.JRadioButton();
        radBut = new javax.swing.JRadioButton();
        lblBkPic2 = new javax.swing.JLabel();
        panelCost = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCarTitle = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        tFieldCarSalePrice = new javax.swing.JTextField();
        tFieldTradeInVal = new javax.swing.JTextField();
        tFieldFeaturesCost = new javax.swing.JTextField();
        tFieldTotalTax = new javax.swing.JTextField();
        tFieldYouSave = new javax.swing.JTextField();
        tFieldCoupon = new javax.swing.JTextField();
        butCompute = new javax.swing.JButton();
        butClear = new javax.swing.JButton();
        lblAuthor = new javax.swing.JLabel();
        tFieldAmountDue1 = new javax.swing.JTextField();
        lbl7 = new javax.swing.JLabel();
        LblCouponInfo = new javax.swing.JLabel();
        lblOurPrice = new javax.swing.JLabel();
        lblBkPic1 = new javax.swing.JLabel();
        panelControl = new javax.swing.JPanel();
        butSummary = new javax.swing.JButton();
        butSave = new javax.swing.JButton();
        butExit = new javax.swing.JButton();
        butTaxSummary = new javax.swing.JButton();
        butPriceList = new javax.swing.JButton();
        butHelp = new javax.swing.JButton();
        lblBkPic4 = new javax.swing.JLabel();
        panelImg = new javax.swing.JPanel();
        lblDefultCarPic = new javax.swing.JLabel();
        lblVoltPic = new javax.swing.JLabel();
        lblCruzePic = new javax.swing.JLabel();
        lblEquinoxPic = new javax.swing.JLabel();
        panelFeature = new javax.swing.JPanel();
        cBoxTran = new javax.swing.JCheckBox();
        cBox17 = new javax.swing.JCheckBox();
        cBoxFog = new javax.swing.JCheckBox();
        cBoxSeat = new javax.swing.JCheckBox();
        cBoxSpeaker = new javax.swing.JCheckBox();
        lblBkPic3 = new javax.swing.JLabel();
        lblBkPic6 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        mItemCompute = new javax.swing.JMenuItem();
        mItemSave = new javax.swing.JMenuItem();
        mItemOpen = new javax.swing.JMenuItem();
        separatorFile = new javax.swing.JPopupMenu.Separator();
        mItemClear = new javax.swing.JMenuItem();
        mItemExit = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        mItemHelp = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        separatorView = new javax.swing.JPopupMenu.Separator();
        mItemPriceList = new javax.swing.JMenuItem();
        mItemSummary = new javax.swing.JMenuItem();
        mItemTaxSummary = new javax.swing.JMenuItem();

        lblBkPic5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NavyBlue.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chevrolet Car 2015 Sale");
        setFont(new java.awt.Font("Adobe Devanagari", 1, 14)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.FlowLayout());

        mainPanel.setMaximumSize(new java.awt.Dimension(660, 575));
        mainPanel.setMinimumSize(new java.awt.Dimension(660, 575));
        mainPanel.setPreferredSize(new java.awt.Dimension(660, 575));
        mainPanel.setLayout(null);

        panelVehicle.setBackground(new java.awt.Color(255, 255, 255));
        panelVehicle.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehicle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 14))); // NOI18N
        panelVehicle.setMaximumSize(new java.awt.Dimension(500, 100));
        panelVehicle.setMinimumSize(new java.awt.Dimension(500, 100));
        panelVehicle.setPreferredSize(new java.awt.Dimension(500, 100));
        panelVehicle.setLayout(null);

        radButCruze.setBackground(new java.awt.Color(255, 255, 255));
        butGroupCar.add(radButCruze);
        radButCruze.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        radButCruze.setForeground(new java.awt.Color(255, 255, 255));
        radButCruze.setText("Cruze LS");
        radButCruze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radButCruzeActionPerformed(evt);
            }
        });
        panelVehicle.add(radButCruze);
        radButCruze.setBounds(16, 28, 103, 27);

        radButEquinox.setBackground(new java.awt.Color(255, 255, 255));
        butGroupCar.add(radButEquinox);
        radButEquinox.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        radButEquinox.setForeground(new java.awt.Color(255, 255, 255));
        radButEquinox.setText("Equinox LS");
        radButEquinox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radButEquinoxActionPerformed(evt);
            }
        });
        panelVehicle.add(radButEquinox);
        radButEquinox.setBounds(146, 28, 119, 27);

        radButVolt.setBackground(new java.awt.Color(255, 255, 255));
        butGroupCar.add(radButVolt);
        radButVolt.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        radButVolt.setForeground(new java.awt.Color(255, 255, 255));
        radButVolt.setText("Volt");
        radButVolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radButVoltActionPerformed(evt);
            }
        });
        panelVehicle.add(radButVolt);
        radButVolt.setBounds(302, 28, 61, 27);

        radBut1.setBackground(new java.awt.Color(255, 255, 255));
        radBut1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        radBut1.setForeground(new java.awt.Color(255, 255, 255));
        radBut1.setText("Malibu");
        radBut1.setEnabled(false);
        panelVehicle.add(radBut1);
        radBut1.setBounds(449, 28, 81, 27);

        radBut.setBackground(new java.awt.Color(255, 255, 255));
        radBut.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 16)); // NOI18N
        radBut.setForeground(new java.awt.Color(255, 255, 255));
        radBut.setText("Impala");
        radBut.setEnabled(false);
        panelVehicle.add(radBut);
        radBut.setBounds(550, 28, 83, 27);

        lblBkPic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NavyBlue.png"))); // NOI18N
        panelVehicle.add(lblBkPic2);
        lblBkPic2.setBounds(-10, -90, 2560, 1600);

        mainPanel.add(panelVehicle);
        panelVehicle.setBounds(0, 0, 660, 77);

        panelCost.setBackground(new java.awt.Color(255, 255, 255));
        panelCost.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cost Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 14))); // NOI18N
        panelCost.setMaximumSize(new java.awt.Dimension(350, 430));
        panelCost.setMinimumSize(new java.awt.Dimension(350, 430));
        panelCost.setPreferredSize(new java.awt.Dimension(350, 430));
        panelCost.setLayout(null);

        lblDate.setBackground(new java.awt.Color(255, 255, 255));
        lblDate.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 15)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        panelCost.add(lblDate);
        lblDate.setBounds(120, 0, 220, 20);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Record Date:");
        jLabel1.setEnabled(false);
        panelCost.add(jLabel1);
        jLabel1.setBounds(20, 0, 90, 15);

        lblCarTitle.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 13)); // NOI18N
        lblCarTitle.setForeground(new java.awt.Color(255, 255, 255));
        panelCost.add(lblCarTitle);
        lblCarTitle.setBounds(20, 10, 110, 20);

        lbl1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("Car's Sales Price:");
        panelCost.add(lbl1);
        lbl1.setBounds(20, 42, 118, 18);

        lbl2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("Trade-In Value:");
        panelCost.add(lbl2);
        lbl2.setBounds(20, 109, 98, 18);

        lbl3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setText("Features Cost:");
        panelCost.add(lbl3);
        lbl3.setBounds(20, 155, 98, 18);

        lbl4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 255, 255));
        lbl4.setText("Tax (8%):");
        panelCost.add(lbl4);
        lbl4.setBounds(20, 200, 63, 18);

        lbl5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        lbl5.setForeground(new java.awt.Color(255, 255, 255));
        lbl5.setText("You Save:");
        panelCost.add(lbl5);
        lbl5.setBounds(20, 245, 67, 18);

        lbl6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        lbl6.setForeground(new java.awt.Color(255, 255, 255));
        lbl6.setText("Amount Due:");
        panelCost.add(lbl6);
        lbl6.setBounds(20, 294, 86, 18);

        tFieldCarSalePrice.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tFieldCarSalePrice.setMaximumSize(new java.awt.Dimension(75, 24));
        tFieldCarSalePrice.setMinimumSize(new java.awt.Dimension(75, 24));
        tFieldCarSalePrice.setPreferredSize(new java.awt.Dimension(75, 24));
        panelCost.add(tFieldCarSalePrice);
        tFieldCarSalePrice.setBounds(167, 40, 154, 24);

        tFieldTradeInVal.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tFieldTradeInVal.setMaximumSize(new java.awt.Dimension(75, 24));
        tFieldTradeInVal.setMinimumSize(new java.awt.Dimension(75, 24));
        tFieldTradeInVal.setPreferredSize(new java.awt.Dimension(75, 24));
        panelCost.add(tFieldTradeInVal);
        tFieldTradeInVal.setBounds(167, 107, 154, 24);

        tFieldFeaturesCost.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tFieldFeaturesCost.setEnabled(false);
        tFieldFeaturesCost.setMaximumSize(new java.awt.Dimension(75, 24));
        tFieldFeaturesCost.setMinimumSize(new java.awt.Dimension(75, 24));
        tFieldFeaturesCost.setPreferredSize(new java.awt.Dimension(75, 24));
        panelCost.add(tFieldFeaturesCost);
        tFieldFeaturesCost.setBounds(167, 153, 154, 24);

        tFieldTotalTax.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tFieldTotalTax.setEnabled(false);
        tFieldTotalTax.setMaximumSize(new java.awt.Dimension(75, 24));
        tFieldTotalTax.setMinimumSize(new java.awt.Dimension(75, 24));
        tFieldTotalTax.setPreferredSize(new java.awt.Dimension(75, 24));
        panelCost.add(tFieldTotalTax);
        tFieldTotalTax.setBounds(167, 198, 154, 24);

        tFieldYouSave.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tFieldYouSave.setEnabled(false);
        tFieldYouSave.setMaximumSize(new java.awt.Dimension(75, 24));
        tFieldYouSave.setMinimumSize(new java.awt.Dimension(75, 24));
        tFieldYouSave.setPreferredSize(new java.awt.Dimension(75, 24));
        panelCost.add(tFieldYouSave);
        tFieldYouSave.setBounds(167, 243, 154, 24);

        tFieldCoupon.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tFieldCoupon.setText("0");
        tFieldCoupon.setMaximumSize(new java.awt.Dimension(75, 24));
        tFieldCoupon.setMinimumSize(new java.awt.Dimension(75, 24));
        tFieldCoupon.setPreferredSize(new java.awt.Dimension(75, 24));
        tFieldCoupon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tFieldCouponKeyTyped(evt);
            }
        });
        panelCost.add(tFieldCoupon);
        tFieldCoupon.setBounds(167, 328, 160, 24);

        butCompute.setBackground(new java.awt.Color(0, 153, 204));
        butCompute.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        butCompute.setText("Compute");
        butCompute.setMaximumSize(new java.awt.Dimension(89, 30));
        butCompute.setMinimumSize(new java.awt.Dimension(89, 30));
        butCompute.setPreferredSize(new java.awt.Dimension(89, 30));
        butCompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butComputeActionPerformed(evt);
            }
        });
        panelCost.add(butCompute);
        butCompute.setBounds(34, 388, 89, 30);

        butClear.setBackground(new java.awt.Color(0, 153, 204));
        butClear.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        butClear.setText("Clear");
        butClear.setMaximumSize(new java.awt.Dimension(65, 30));
        butClear.setMinimumSize(new java.awt.Dimension(65, 30));
        butClear.setPreferredSize(new java.awt.Dimension(65, 30));
        butClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butClearActionPerformed(evt);
            }
        });
        panelCost.add(butClear);
        butClear.setBounds(265, 388, 65, 30);

        lblAuthor.setForeground(new java.awt.Color(153, 153, 153));
        lblAuthor.setText("Author: Kevin Chen");
        panelCost.add(lblAuthor);
        lblAuthor.setBounds(10, 420, 111, 15);

        tFieldAmountDue1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        tFieldAmountDue1.setEnabled(false);
        tFieldAmountDue1.setMaximumSize(new java.awt.Dimension(75, 24));
        tFieldAmountDue1.setMinimumSize(new java.awt.Dimension(75, 24));
        tFieldAmountDue1.setPreferredSize(new java.awt.Dimension(75, 24));
        panelCost.add(tFieldAmountDue1);
        tFieldAmountDue1.setBounds(167, 292, 154, 24);

        lbl7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        lbl7.setForeground(new java.awt.Color(255, 255, 255));
        lbl7.setText("Coupon Number:");
        panelCost.add(lbl7);
        lbl7.setBounds(20, 330, 114, 18);

        LblCouponInfo.setForeground(new java.awt.Color(255, 255, 255));
        LblCouponInfo.setText("Apply coupon discount here");
        panelCost.add(LblCouponInfo);
        LblCouponInfo.setBounds(133, 359, 166, 15);

        lblOurPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblOurPrice.setText("Our Price:");
        panelCost.add(lblOurPrice);
        lblOurPrice.setBounds(167, 18, 58, 15);

        lblBkPic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NavyBlue.png"))); // NOI18N
        panelCost.add(lblBkPic1);
        lblBkPic1.setBounds(0, 0, 2560, 1600);

        mainPanel.add(panelCost);
        panelCost.setBounds(0, 80, 350, 440);

        panelControl.setBackground(new java.awt.Color(255, 255, 255));
        panelControl.setMaximumSize(new java.awt.Dimension(660, 60));
        panelControl.setMinimumSize(new java.awt.Dimension(660, 60));
        panelControl.setPreferredSize(new java.awt.Dimension(660, 60));
        panelControl.setLayout(null);

        butSummary.setBackground(new java.awt.Color(0, 153, 204));
        butSummary.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        butSummary.setText("Summary");
        butSummary.setMaximumSize(new java.awt.Dimension(135, 28));
        butSummary.setMinimumSize(new java.awt.Dimension(135, 28));
        butSummary.setPreferredSize(new java.awt.Dimension(135, 30));
        butSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSummaryActionPerformed(evt);
            }
        });
        panelControl.add(butSummary);
        butSummary.setBounds(110, 10, 100, 30);

        butSave.setBackground(new java.awt.Color(0, 153, 204));
        butSave.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        butSave.setText("Save");
        butSave.setMaximumSize(new java.awt.Dimension(55, 28));
        butSave.setMinimumSize(new java.awt.Dimension(55, 28));
        butSave.setPreferredSize(new java.awt.Dimension(55, 30));
        butSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSaveActionPerformed(evt);
            }
        });
        panelControl.add(butSave);
        butSave.setBounds(480, 10, 72, 30);

        butExit.setBackground(new java.awt.Color(0, 153, 204));
        butExit.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        butExit.setText("Exit");
        butExit.setMaximumSize(new java.awt.Dimension(55, 28));
        butExit.setMinimumSize(new java.awt.Dimension(55, 28));
        butExit.setPreferredSize(new java.awt.Dimension(55, 30));
        butExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExitActionPerformed(evt);
            }
        });
        panelControl.add(butExit);
        butExit.setBounds(570, 10, 72, 30);

        butTaxSummary.setBackground(new java.awt.Color(0, 153, 204));
        butTaxSummary.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        butTaxSummary.setText("Tax Summary");
        butTaxSummary.setMaximumSize(new java.awt.Dimension(119, 28));
        butTaxSummary.setMinimumSize(new java.awt.Dimension(119, 28));
        butTaxSummary.setPreferredSize(new java.awt.Dimension(135, 30));
        butTaxSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTaxSummaryActionPerformed(evt);
            }
        });
        panelControl.add(butTaxSummary);
        butTaxSummary.setBounds(230, 10, 120, 30);

        butPriceList.setBackground(new java.awt.Color(0, 153, 204));
        butPriceList.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        butPriceList.setText("Price List");
        butPriceList.setMaximumSize(new java.awt.Dimension(91, 28));
        butPriceList.setMinimumSize(new java.awt.Dimension(91, 28));
        butPriceList.setPreferredSize(new java.awt.Dimension(91, 30));
        butPriceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPriceListActionPerformed(evt);
            }
        });
        panelControl.add(butPriceList);
        butPriceList.setBounds(370, 10, 90, 30);

        butHelp.setBackground(new java.awt.Color(0, 153, 204));
        butHelp.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        butHelp.setText("Help");
        butHelp.setMaximumSize(new java.awt.Dimension(55, 28));
        butHelp.setMinimumSize(new java.awt.Dimension(55, 28));
        butHelp.setPreferredSize(new java.awt.Dimension(55, 30));
        butHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butHelpActionPerformed(evt);
            }
        });
        panelControl.add(butHelp);
        butHelp.setBounds(14, 11, 72, 30);

        lblBkPic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NavyBlue.png"))); // NOI18N
        lblBkPic4.setPreferredSize(new java.awt.Dimension(1000, 1000));
        panelControl.add(lblBkPic4);
        lblBkPic4.setBounds(-110, -180, 1000, 780);

        mainPanel.add(panelControl);
        panelControl.setBounds(0, 520, 660, 56);

        panelImg.setBackground(new java.awt.Color(255, 204, 204));
        panelImg.setMaximumSize(new java.awt.Dimension(300, 160));
        panelImg.setMinimumSize(new java.awt.Dimension(300, 160));
        panelImg.setPreferredSize(new java.awt.Dimension(300, 160));
        panelImg.setLayout(null);

        lblDefultCarPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/defultCarPic.jpg"))); // NOI18N
        panelImg.add(lblDefultCarPic);
        lblDefultCarPic.setBounds(0, 0, 300, 180);

        lblVoltPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/voPic.jpg"))); // NOI18N
        panelImg.add(lblVoltPic);
        lblVoltPic.setBounds(0, 0, 300, 180);

        lblCruzePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/crPic.jpg"))); // NOI18N
        panelImg.add(lblCruzePic);
        lblCruzePic.setBounds(0, 0, 300, 180);

        lblEquinoxPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eqPic.jpg"))); // NOI18N
        panelImg.add(lblEquinoxPic);
        lblEquinoxPic.setBounds(0, 0, 300, 180);

        mainPanel.add(panelImg);
        panelImg.setBounds(360, 340, 300, 180);

        panelFeature.setBackground(new java.awt.Color(255, 255, 255));
        panelFeature.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Feature Option", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 14))); // NOI18N
        panelFeature.setMaximumSize(new java.awt.Dimension(260, 260));
        panelFeature.setMinimumSize(new java.awt.Dimension(260, 260));
        panelFeature.setPreferredSize(new java.awt.Dimension(260, 260));
        panelFeature.setLayout(null);

        cBoxTran.setBackground(new java.awt.Color(255, 255, 255));
        cBoxTran.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        cBoxTran.setForeground(new java.awt.Color(255, 255, 255));
        cBoxTran.setText("Automate transmission");
        panelFeature.add(cBoxTran);
        cBoxTran.setBounds(16, 28, 181, 27);

        cBox17.setBackground(new java.awt.Color(255, 255, 255));
        cBox17.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        cBox17.setForeground(new java.awt.Color(255, 255, 255));
        cBox17.setText("17\" 5-spoke painted alumiun");
        panelFeature.add(cBox17);
        cBox17.setBounds(16, 73, 213, 27);

        cBoxFog.setBackground(new java.awt.Color(255, 255, 255));
        cBoxFog.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        cBoxFog.setForeground(new java.awt.Color(255, 255, 255));
        cBoxFog.setText("Front fog lamps ");
        panelFeature.add(cBoxFog);
        cBoxFog.setBounds(16, 118, 137, 27);

        cBoxSeat.setBackground(new java.awt.Color(255, 255, 255));
        cBoxSeat.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        cBoxSeat.setForeground(new java.awt.Color(255, 255, 255));
        cBoxSeat.setText("Power seat");
        panelFeature.add(cBoxSeat);
        cBoxSeat.setBounds(16, 163, 103, 27);

        cBoxSpeaker.setBackground(new java.awt.Color(255, 255, 255));
        cBoxSpeaker.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        cBoxSpeaker.setForeground(new java.awt.Color(255, 255, 255));
        cBoxSpeaker.setText("Pioneer 6 way speaker");
        panelFeature.add(cBoxSpeaker);
        cBoxSpeaker.setBounds(16, 208, 179, 27);

        lblBkPic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NavyBlue.png"))); // NOI18N
        lblBkPic3.setMaximumSize(new java.awt.Dimension(1000, 1000));
        lblBkPic3.setMinimumSize(new java.awt.Dimension(1000, 1000));
        lblBkPic3.setPreferredSize(new java.awt.Dimension(1000, 1000));
        panelFeature.add(lblBkPic3);
        lblBkPic3.setBounds(-672, -432, 1420, 1010);

        mainPanel.add(panelFeature);
        panelFeature.setBounds(360, 80, 300, 257);

        lblBkPic6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NavyBlue.png"))); // NOI18N
        mainPanel.add(lblBkPic6);
        lblBkPic6.setBounds(-80, -20, 2720, 1630);

        getContentPane().add(mainPanel);

        menuFile.setText("File");
        menuFile.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });

        mItemCompute.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        mItemCompute.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mItemCompute.setText("Compute");
        mItemCompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemComputeActionPerformed(evt);
            }
        });
        menuFile.add(mItemCompute);

        mItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mItemSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mItemSave.setText("Save");
        mItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSaveActionPerformed(evt);
            }
        });
        menuFile.add(mItemSave);

        mItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mItemOpen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mItemOpen.setText("Open");
        mItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemOpenActionPerformed(evt);
            }
        });
        menuFile.add(mItemOpen);
        menuFile.add(separatorFile);

        mItemClear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        mItemClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mItemClear.setText("Clear");
        mItemClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemClearActionPerformed(evt);
            }
        });
        menuFile.add(mItemClear);

        mItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mItemExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mItemExit.setText("Exit");
        mItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemExitActionPerformed(evt);
            }
        });
        menuFile.add(mItemExit);

        menuBar.add(menuFile);

        menuView.setText("View");
        menuView.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        mItemHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mItemHelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mItemHelp.setText("Help");
        mItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemHelpActionPerformed(evt);
            }
        });
        menuView.add(mItemHelp);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setText("File Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuView.add(jMenuItem1);
        menuView.add(separatorView);

        mItemPriceList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mItemPriceList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mItemPriceList.setText("Price List");
        mItemPriceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemPriceListActionPerformed(evt);
            }
        });
        menuView.add(mItemPriceList);

        mItemSummary.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mItemSummary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mItemSummary.setText("Summary");
        mItemSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemSummaryActionPerformed(evt);
            }
        });
        menuView.add(mItemSummary);

        mItemTaxSummary.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mItemTaxSummary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mItemTaxSummary.setText("Tax Summary");
        mItemTaxSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mItemTaxSummaryActionPerformed(evt);
            }
        });
        menuView.add(mItemTaxSummary);

        menuBar.add(menuView);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExitActionPerformed
       System.exit(1);
    }//GEN-LAST:event_butExitActionPerformed

    private void butSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSummaryActionPerformed
        SummaryUI summary = new SummaryUI ();
        summary.setLocationRelativeTo(this);
        summary.setVisible(true);
    }//GEN-LAST:event_butSummaryActionPerformed

    private void butTaxSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTaxSummaryActionPerformed
        TaxSummaryUI taxSummary= new TaxSummaryUI();
        taxSummary.setLocationRelativeTo(this);
        taxSummary.setVisible(true);
    }//GEN-LAST:event_butTaxSummaryActionPerformed

    private void butPriceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPriceListActionPerformed
        PriceListUI PriceList= new PriceListUI();
        PriceList.setLocationRelativeTo(this);
        PriceList.setVisible(true);
    }//GEN-LAST:event_butPriceListActionPerformed

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed
        System.exit(1);
    }//GEN-LAST:event_menuFileActionPerformed

    private void mItemSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSummaryActionPerformed
      butSummary.doClick();
    }//GEN-LAST:event_mItemSummaryActionPerformed

    private void mItemTaxSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemTaxSummaryActionPerformed
        butTaxSummary.doClick();
    }//GEN-LAST:event_mItemTaxSummaryActionPerformed

    private void mItemPriceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemPriceListActionPerformed
       butPriceList.doClick();
    }//GEN-LAST:event_mItemPriceListActionPerformed

    private void radButCruzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radButCruzeActionPerformed
        if (radButCruze.isSelected())
        {
            lblCarTitle.setText("2015Cruze");
             tFieldCarSalePrice.setText("17500"); // Human Code
             tFieldTradeInVal.setText("0");
             
           radButEquinox.setEnabled(false);
           radButVolt.setEnabled(false);
           
             lblCruzePic.setVisible(true);
             lblEquinoxPic.setVisible(false);
             lblVoltPic.setVisible(false);
             lblDefultCarPic.setVisible(false);
        }
    }//GEN-LAST:event_radButCruzeActionPerformed

    private void radButEquinoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radButEquinoxActionPerformed
        if (radButEquinox.isSelected())
        {
            lblCarTitle.setText("2015Equinox");
             tFieldCarSalePrice.setText("21500"); // Human Code
              tFieldTradeInVal.setText("0");
              
             radButVolt.setEnabled(false);
             radButCruze.setEnabled(false);
     
             
             cBoxSeat.doClick();
             cBoxSeat.setEnabled(false);
             
             lblCruzePic.setVisible(false);
             lblEquinoxPic.setVisible(true);
             lblVoltPic.setVisible(false);
             lblDefultCarPic.setVisible(false);
        }
    }//GEN-LAST:event_radButEquinoxActionPerformed

    private void radButVoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radButVoltActionPerformed
        if (radButVolt.isSelected())
        {
            lblCarTitle.setText("2015Volt");
             tFieldCarSalePrice.setText("34000"); // Human Code
              tFieldTradeInVal.setText("0");
             
             radButEquinox.setEnabled(false);
             radButCruze.setEnabled(false);
             
             cBoxTran.doClick();
             cBoxTran.setEnabled(false);
                     
              cBoxFog.doClick();
              cBoxFog.setEnabled(false);
                      
              cBoxSeat.doClick();
              cBoxSeat.setEnabled(false);      
                       
               lblCruzePic.setVisible(false);
             lblEquinoxPic.setVisible(false);
             lblVoltPic.setVisible(true);   
             lblDefultCarPic.setVisible(false);
        }
    }//GEN-LAST:event_radButVoltActionPerformed

    private void butClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butClearActionPerformed
        //set Radio button to Enabled and Unselect 
        lblDate.setText("");
        lblCarTitle.setText("");
        
         radButEquinox.setEnabled(true);
         radButCruze.setEnabled(true);
         radButVolt.setEnabled(true);
         
         tFieldCoupon.setEditable(true);
         
         butCompute.setEnabled(true);
        
         radButEquinox.setSelected(false);
         radButVolt.setSelected(false);
         radButCruze.setSelected(false);
      
         //Set Cost Info textBox to empty 
        tFieldCarSalePrice.setText("");
        tFieldTradeInVal.setText("");
        tFieldFeaturesCost.setText("");
        tFieldTotalTax.setText("");
        tFieldYouSave.setText("");
        tFieldAmountDue1.setText("");
        tFieldCoupon.setText("");
        
        //Set Feature Chect-box to uncheck
        cBoxTran.setSelected(false);
        cBox17.setSelected(false);
        cBoxFog.setSelected(false);
        cBoxSeat.setSelected(false);
        cBoxSpeaker.setSelected(false);
        
        cBoxTran.setEnabled(true);
        cBox17.setEnabled(true);
        cBoxFog.setEnabled(true);
        cBoxSeat.setEnabled(true);
        cBoxSpeaker.setEnabled(true);
        
        tFieldCoupon.setText("0");
        
             lblCruzePic.setVisible(false);
             lblEquinoxPic.setVisible(false);
             lblVoltPic.setVisible(false);
             lblDefultCarPic.setVisible(true);
             
    }//GEN-LAST:event_butClearActionPerformed

    private void butComputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butComputeActionPerformed
     

        if (Validator.isTextFieldPositive(tFieldCarSalePrice)) {
            if (Validator.isTextFieldNonNegative(tFieldTradeInVal)) {
                if(Validator.isTextFieldNotEmpty(tFieldCoupon)){
                
                                    
                
                 if ( radButCruze.isSelected()) { //Call Cruze Class
                        
                        callCruzeClass();
                        }

                   else if (radButEquinox.isSelected()) { //Call Equinox Class
                         
                        callEquinoxClass();                       
                        }
                  
                       else if (radButVolt.isSelected()) { //Call Volt Class
                        
                            callVoltClass ();
                        }
                
      
            
                              }
        
                        }
        }
        
        cBoxTran.setEnabled(false);
        cBox17.setEnabled(false);
        cBoxFog.setEnabled(false);
        cBoxSeat.setEnabled(false);
        cBoxSpeaker.setEnabled(false);
        
        tFieldCoupon.setEditable(false);
        butCompute.setEnabled(false);
        
        
        rCheckBoxSave ();
    }//GEN-LAST:event_butComputeActionPerformed

    private void mItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemExitActionPerformed
    butExit.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_mItemExitActionPerformed

    private void butHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butHelpActionPerformed
        HelpUI help = new HelpUI ();
        help.setLocationRelativeTo(this);
        help.setVisible(true);
    }//GEN-LAST:event_butHelpActionPerformed

    private void mItemComputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemComputeActionPerformed
        butCompute.doClick();
    }//GEN-LAST:event_mItemComputeActionPerformed

    private void mItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemHelpActionPerformed
        butHelp.doClick();
    }//GEN-LAST:event_mItemHelpActionPerformed

    private void tFieldCouponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFieldCouponKeyTyped
        char c = evt.getKeyChar();
        if (! (Character.isDigit(c) || c==KeyEvent.VK_BACKSPACE) || c==KeyEvent.VK_DELETE)
        evt.consume();
        
    }//GEN-LAST:event_tFieldCouponKeyTyped

    private void mItemClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemClearActionPerformed
       mItemClear.doClick();
    }//GEN-LAST:event_mItemClearActionPerformed

    private void mItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemSaveActionPerformed
       
        boolean fileExist = false;

        FileFilterTxt ff = new FileFilterTxt ();
        fc.setAcceptAllFileFilterUsed(false);//--

   
        fc.setCurrentDirectory(new File (System.getProperty("user.dir")));//Defult the Directory
        fc.setDialogTitle("Circle App File Save");//Title of the JFileChooser 
        fc.setFileFilter(new FileFilterTxt());
        int result = fc.showSaveDialog(mItemSave);//Show JFileChooser Save Dialog

        if (result == JFileChooser.APPROVE_OPTION) 
        {
            try{     
                    
                
                       f = fc.getSelectedFile();//Created file object           
                      if (!ff.accept(f))  // if File type is not ture
                      {
                          JOptionPane.showMessageDialog(null, "This is wrong file type   ( txt Only ! )"
                                      , "InfoBox: " + "File Type Error", JOptionPane.ERROR_MESSAGE);  
                      }
                 else 
                            {   fileExist = f.exists() && !f.isDirectory();// !!!!!!!!!!!!!!!!! Check if  File Exist Or not!!!!!!!!!!!!!!
                              // String path = f.getAbsolutePath(); 
                             // File nf1 = new File (path);    //get real FilePath

                              
                              FileWriter fw = new FileWriter(f); //Place .txt defult the file type                          

                          if  (fileExist == true )//Check if File Exit or not ?
                              {    //if File have already exist Error Message show to user
                                       fw.close();     //Close Writer
                                         
                                     //  nf1.delete();              //File Delete                    
                                       JOptionPane.showMessageDialog(null, "The file have already exist"
                                         , "InfoBox: " + "File Save Error", JOptionPane.ERROR_MESSAGE);  

                              }
                                
                      else {
                              String dateString = (date.toString()); 
                              dateString = dateString.replaceAll(" ", "");//Replace all white space inside of String
                               
                               fw.write(dateString+"       "+lblCarTitle.getText()+"       "+tFieldCarSalePrice.getText()+"        "+
                                       tFieldTradeInVal.getText()+"        "+tFieldFeaturesCost.getText()+"     "+
                                       tFieldTotalTax.getText()+"      "+tFieldYouSave.getText()+
                                       "       "+tFieldAmountDue1.getText()+"        "+tFieldCoupon.getText()+
                                      "       "+checkButArray[0]+"       "+ checkButArray[1]+"       "+ checkButArray[2]+"       "+ 
                                       "       "+checkButArray[3]+"       "+ checkButArray[4]+"      "+nl+nl+nl+nl+nl+nl+filedIdentifer
                               );
                                       
                                       
                                       
   
                                      fw.close();//Finish writing close file

                                    JOptionPane.showMessageDialog(null, "Your file have save at: \n"//MessageBox show File Save
                                    +f.getPath() , "InfoBox: " + "File Save Info", JOptionPane.INFORMATION_MESSAGE);

                            
                         }
            
                 }
            }//File type not ture
            catch (Exception ex) { JOptionPane.showMessageDialog(null, "Error !  Can't save the file. ", "InfoBox: " 
                        + "File Save Error", JOptionPane.ERROR_MESSAGE);}//File Save Error
        } 
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_mItemSaveActionPerformed

    private void butSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSaveActionPerformed
       mItemSave.doClick();
    }//GEN-LAST:event_butSaveActionPerformed

    private void mItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mItemOpenActionPerformed
       jLabel1.setVisible(true);
        
        
        boolean found = true; 
        
        boolean found0=false; 
        boolean found1=false; 
        boolean found2=false; 
        boolean found3=false; 
        boolean found4=false;
        boolean found5=false; 
        boolean found6=false; 
        boolean found7=false;
        checkButArray [0] ="cBox100";
        checkButArray [1] ="cBox101";
        checkButArray [2] ="cBox102";
        checkButArray [3] ="cBox103";
        checkButArray [4] ="cBox104";
        
        checkButArray [5] ="radB100";
        checkButArray [6] ="radB101";
        checkButArray [7] ="radB102";
        
        fc.setCurrentDirectory(new File (System.getProperty("user.dir"))); //set FileChooser Defult Directory
        int result = fc.showOpenDialog(mItemOpen); //Dialog menu Open
        
        if (result == JFileChooser.APPROVE_OPTION) 
        {
            
                try {
                        f= fc.getSelectedFile(); //FileChooser Object pass to file
                                          
                        s = new Scanner (f); //File Object pass to Scanner
                      
                       
                    FileSearch fs = new FileSearch();
                    found = fs.find(f, (filedIdentifer));

                    
                                        
                        if (found == true )//Have to use Boolean method becase of the nested hasNext Statement!!!!!!!!!!!!!
                        {
                             found5 = fs.find(f, (checkButArray  [5]));
                             found6 = fs.find(f, (checkButArray  [6]));
                             found7 = fs.find(f, (checkButArray  [7]));
                               if (found5 = true){ radButCruze.doClick();      }
                               if (found6 = true){ radButEquinox.doClick();        }
                               if (found7 = true){ radButVolt.doClick();     }
                            
                                    while (s.hasNext()) 
                                    {                                                                                                                                             
                                               lblDate.setText                  (   s.next()     );

                                               lblCarTitle.setText              (   s.next()     );
                                               tFieldCarSalePrice.setText    (   s.next()     );                                             
                                               
                                               tFieldTradeInVal.setText      (   s.next()     );
                                               tFieldFeaturesCost.setText   (   s.next()     );
                                               tFieldTotalTax.setText         (   s.next()     );  
                                               
                                               tFieldYouSave.setText         (   s.next()     );
                                               tFieldAmountDue1.setText    (   s.next()     );
                                               tFieldCoupon.setText           (   s.next()     );                                                                    
                                               
                                                s.close();

                                   //            FileSearch fs2 = new FileSearch();
                                               found0 = fs.find(f, (checkButArray  [0]));
                                               found1 = fs.find(f, (checkButArray  [1]));
                                               found2 = fs.find(f, (checkButArray  [2]));
                                               found3 = fs.find(f, (checkButArray  [3]));
                                               found4 = fs.find(f, (checkButArray  [4]));
                                               
                                               if (found0 == true){ cBoxTran.doClick();      }
                                               if (found1 == true){ cBox17.doClick();        }
                                               if (found2 == true){ cBoxFog.doClick();     }
                                               if (found3 == true){ cBoxSeat.doClick();      }
                                               if (found4 == true){ cBoxSpeaker.doClick();  }
                                               
                                               cBoxTran.setEnabled(false);
                                               cBox17.setEnabled(false);
                                               cBoxFog.setEnabled(false);
                                               cBoxSeat.setEnabled(false);
                                               cBoxSpeaker.setEnabled(false);
                                              
                                              
                                    }     
                                  
                        }
                        else 
                        {
                                            JOptionPane.showMessageDialog(null, "This is a unidentified file\n"
                                              + "Please Try again.", "InfoBox: " + "Unidentified File Error", 
                                             JOptionPane.ERROR_MESSAGE);  //Message to the user App File not Found
                                            butClear.doClick();
                        }
                        
                        
                                   
                    }
                     catch (Exception ex) {/*JOptionPane.showMessageDialog(null, "File Cannot be open !", "InfoBox: " + "File Open Error", JOptionPane.ERROR_MESSAGE); */}     
        }
       s.close();

        
        
        
    }//GEN-LAST:event_mItemOpenActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      jLabel1.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
         FileHelp help = new FileHelp ();
        help.setLocationRelativeTo(this);
        help.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarSaleMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarSaleMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarSaleMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarSaleMainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarSaleMainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblCouponInfo;
    private javax.swing.JButton butClear;
    private javax.swing.JButton butCompute;
    private javax.swing.JButton butExit;
    private javax.swing.ButtonGroup butGroupCar;
    private javax.swing.JButton butHelp;
    private javax.swing.JButton butPriceList;
    private javax.swing.JButton butSave;
    private javax.swing.JButton butSummary;
    private javax.swing.JButton butTaxSummary;
    private javax.swing.JCheckBox cBox17;
    private javax.swing.JCheckBox cBoxFog;
    private javax.swing.JCheckBox cBoxSeat;
    private javax.swing.JCheckBox cBoxSpeaker;
    private javax.swing.JCheckBox cBoxTran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblBkPic1;
    private javax.swing.JLabel lblBkPic2;
    private javax.swing.JLabel lblBkPic3;
    private javax.swing.JLabel lblBkPic4;
    private javax.swing.JLabel lblBkPic5;
    private javax.swing.JLabel lblBkPic6;
    private javax.swing.JLabel lblCarTitle;
    private javax.swing.JLabel lblCruzePic;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDefultCarPic;
    private javax.swing.JLabel lblEquinoxPic;
    private javax.swing.JLabel lblOurPrice;
    private javax.swing.JLabel lblVoltPic;
    private javax.swing.JMenuItem mItemClear;
    private javax.swing.JMenuItem mItemCompute;
    private javax.swing.JMenuItem mItemExit;
    private javax.swing.JMenuItem mItemHelp;
    private javax.swing.JMenuItem mItemOpen;
    private javax.swing.JMenuItem mItemPriceList;
    private javax.swing.JMenuItem mItemSave;
    private javax.swing.JMenuItem mItemSummary;
    private javax.swing.JMenuItem mItemTaxSummary;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuView;
    private javax.swing.JPanel panelControl;
    private javax.swing.JPanel panelCost;
    private javax.swing.JPanel panelFeature;
    private javax.swing.JPanel panelImg;
    private javax.swing.JPanel panelVehicle;
    private javax.swing.JRadioButton radBut;
    private javax.swing.JRadioButton radBut1;
    private javax.swing.JRadioButton radButCruze;
    private javax.swing.JRadioButton radButEquinox;
    private javax.swing.JRadioButton radButVolt;
    private javax.swing.JPopupMenu.Separator separatorFile;
    private javax.swing.JPopupMenu.Separator separatorView;
    private javax.swing.JTextField tFieldAmountDue1;
    private javax.swing.JTextField tFieldCarSalePrice;
    private javax.swing.JTextField tFieldCoupon;
    private javax.swing.JTextField tFieldFeaturesCost;
    private javax.swing.JTextField tFieldTotalTax;
    private javax.swing.JTextField tFieldTradeInVal;
    private javax.swing.JTextField tFieldYouSave;
    // End of variables declaration//GEN-END:variables


//----Personal Method Non AutoGen
    
    
    
    //Check Features 
    
    public void callCruzeClass ()
    {
        
     //   Cruze cr = new Cruze
        Cruze cr = new Cruze                 (
        Double.parseDouble(tFieldCarSalePrice.getText()), 
        Double.parseDouble(tFieldTradeInVal.getText()),     
        
        cBoxTran.isSelected(), cBox17.isSelected(),
        cBoxFog.isSelected(), cBoxSeat.isSelected(),
        cBoxSpeaker.isSelected()            );
        
  //Dicount Option---------------------------------------------------------------------------      
        int couponNum = Integer.parseInt(tFieldCoupon.getText());
        Coupon co = new Coupon (couponNum);
        int matchNum = co.getMatch();
        if (matchNum == 2)
        {
            LblCouponInfo.setText("2% Discount Apply");
            cr.getDiscount2();
        }
        if (matchNum == 5)
        {
            LblCouponInfo.setText("5% Discount Apply");
            cr.getDiscount5();
        }
        if (matchNum ==10)
        {
            LblCouponInfo.setText("10% Discount Apply");
            cr.getDiscount10();            
        }
        if (matchNum ==15)
        {
            LblCouponInfo.setText("15% Discount Apply");
            cr.getDiscount15();          
        }
  //End of Discount Option-----------------------------------------------------------------------------      
                
        tFieldCarSalePrice.setText(Formatter.formatCurrency(cr.getCarPrice()));
        tFieldTradeInVal.setText((Double.toString(cr.getTradeIn())));
        tFieldFeaturesCost.setText(Double.toString(cr.getFeatures()));
        tFieldTotalTax.setText(Double.toString(cr.getTax())); 
        
        tFieldYouSave.setText(Double.toString(cr.getYouSave()));
        tFieldAmountDue1.setText(Double.toString(cr.getAmtDue()));

    }
    

    
    public void callEquinoxClass ()
    {
        Equinox eq = new Equinox                                    (
        Double.parseDouble(tFieldCarSalePrice.getText()), 
        Double.parseDouble(tFieldTradeInVal.getText()),     
        
        cBoxTran.isSelected(), cBox17.isSelected(),
        cBoxSeat.isSelected(),cBoxSpeaker.isSelected()        );
        
         //Dicount Option---------------------------------------------------------------------------      
        int couponNum = Integer.parseInt(tFieldCoupon.getText());
        Coupon co = new Coupon (couponNum);
        int matchNum = co.getMatch();
        if (matchNum == 2)
        {
            LblCouponInfo.setText("2% Discount Apply");
            eq.getDiscount2();
        } 
        if (matchNum == 5)
        {
            LblCouponInfo.setText("5% Discount Apply");
            eq.getDiscount5();
        }
        if (matchNum ==10)
        {
            LblCouponInfo.setText("10% Discount Apply");
            eq.getDiscount10();            
        }
        if (matchNum ==15)
        {
            LblCouponInfo.setText("15% Discount Apply");
            eq.getDiscount15();          
        }
  //End of Discount Option-----------------------------------------------------------------------------  
                
        tFieldCarSalePrice.setText(Formatter.formatCurrency(eq.getCarPrice()));
        tFieldTradeInVal.setText((Double.toString(eq.getTradeIn())));
        tFieldFeaturesCost.setText(Double.toString(eq.getFeatures()));
        tFieldTotalTax.setText(Double.toString(eq.getTax())); 
        
        tFieldYouSave.setText(Double.toString(eq.getYouSave()));
        tFieldAmountDue1.setText(Double.toString(eq.getAmtDue()));

      }
    
    
    
    
    public void callVoltClass ()
    {
               Volt vo = new Volt                                    (
        Double.parseDouble(tFieldCarSalePrice.getText()), 
        Double.parseDouble(tFieldTradeInVal.getText()),     
        
        cBox17.isSelected(),
        cBoxSpeaker.isSelected()        );
               
        //Dicount Option---------------------------------------------------------------------------      
        int couponNum = Integer.parseInt(tFieldCoupon.getText());
        Coupon co = new Coupon (couponNum);
        int matchNum = co.getMatch();
        if (matchNum == 2)
        {
            LblCouponInfo.setText("2% Discount Apply");
            vo.getDiscount2();
        }
        if (matchNum == 5)
        {
            LblCouponInfo.setText("5% Discount Apply");
            vo.getDiscount5();
        }
        if (matchNum ==10)
        {
            LblCouponInfo.setText("10% Discount Apply");
            vo.getDiscount10();            
        }
        if (matchNum ==15)
        {
            LblCouponInfo.setText("15% Discount Apply");
            vo.getDiscount15();          
        }
  //End of Discount Option-----------------------------------------------------------------------------          
               
                
        tFieldCarSalePrice.setText(Formatter.formatCurrency(vo.getCarPrice()));
        tFieldTradeInVal.setText((Double.toString(vo.getTradeIn())));
        tFieldFeaturesCost.setText(Double.toString(vo.getFeatures()));
        tFieldTotalTax.setText(Double.toString(vo.getTax())); 
        
        tFieldYouSave.setText(Double.toString(vo.getYouSave()));
        tFieldAmountDue1.setText(Double.toString(vo.getAmtDue()));
    }



    public void rCheckBoxSave () //save checkbox select val
    {
        for (int x = 0; x<checkButArray.length; x++)//clear all val from string array
        {
            checkButArray[x]="";
        }
        
        if (cBoxTran.isSelected()) // 0
        {
            checkButArray [0] ="cBox100";
        } 
        
        if (cBox17.isSelected()) //1
        {
            checkButArray [1] ="cBox101";
        }
        
        if (cBoxFog.isSelected()) //2
        {
            checkButArray [2] ="cBox102";
        }
        
        if (cBoxSeat.isSelected()) //3
        {
            checkButArray [3] ="cBox103";
        }
        
        if (cBoxSpeaker.isSelected()) //4
        {
            checkButArray [4] ="cBox104";
        }
        
        //Radio But
        if (radButCruze.isSelected())
        {
            checkButArray [5] ="radB100";
        }
        
        if(radButEquinox.isSelected())
        {
            checkButArray [6] ="radB101";
        }
        
        if(radButVolt.isSelected())
        {
            checkButArray [7] ="radB102";
        }
      
    }


}


