/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import logic.*;
import java.util.Random;

/**
 *
 * @author woden_000
 */
public class HelpUI extends javax.swing.JFrame {

     CarSaleMainUI mainFrame;
    /**
     * Creates new form Help
     */
    public HelpUI (CarSaleMainUI mainFrame){
        initComponents();
        this.mainFrame = mainFrame; 
    }

    public HelpUI (){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDoc = new javax.swing.JPanel();
        lblHelp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAreaDoc = new javax.swing.JTextArea();
        panelCoupon = new javax.swing.JPanel();
        butGenerate = new javax.swing.JButton();
        lblCoupon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblWon = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Help");
        setBackground(new java.awt.Color(102, 153, 255));

        panelDoc.setBackground(new java.awt.Color(0, 51, 102));

        lblHelp.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblHelp.setForeground(new java.awt.Color(255, 255, 255));
        lblHelp.setText("Help: App Documentation:");

        tAreaDoc.setEditable(false);
        tAreaDoc.setBackground(new java.awt.Color(0, 51, 102));
        tAreaDoc.setColumns(20);
        tAreaDoc.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        tAreaDoc.setForeground(new java.awt.Color(255, 255, 255));
        tAreaDoc.setRows(5);
        tAreaDoc.setText("-Japa Programing Project:\n User Interface and Class \n-How YouSave Work:\n YouSave = MSRP - carPrice + (AmountDue*Discount) \n-How Discount Work:\n  Discount type with coupon Amount: 2%, 5%, 10, 15 \n  When click button Gen.. in the help page the System \n  will generate a unique discount coipon number for \n  you then apply the unique coupon when selecting \n  vehicle.\nThankyou for using this application.");
        tAreaDoc.setEnabled(false);
        tAreaDoc.setSelectionColor(new java.awt.Color(0, 51, 153));
        jScrollPane1.setViewportView(tAreaDoc);

        javax.swing.GroupLayout panelDocLayout = new javax.swing.GroupLayout(panelDoc);
        panelDoc.setLayout(panelDocLayout);
        panelDocLayout.setHorizontalGroup(
            panelDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDocLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHelp)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelDocLayout.setVerticalGroup(
            panelDocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDocLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panelCoupon.setBackground(new java.awt.Color(0, 51, 102));

        butGenerate.setBackground(new java.awt.Color(0, 153, 255));
        butGenerate.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        butGenerate.setText("Generate");
        butGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGenerateActionPerformed(evt);
            }
        });

        lblCoupon.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        lblCoupon.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Your coupon number:");

        lblWon.setBackground(new java.awt.Color(0, 51, 102));
        lblWon.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        lblWon.setForeground(new java.awt.Color(255, 255, 255));

        lblAuthor.setForeground(new java.awt.Color(153, 153, 153));
        lblAuthor.setText("Author: Kevin Chen");

        btnClose.setBackground(new java.awt.Color(0, 153, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCouponLayout = new javax.swing.GroupLayout(panelCoupon);
        panelCoupon.setLayout(panelCouponLayout);
        panelCouponLayout.setHorizontalGroup(
            panelCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCouponLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCouponLayout.createSequentialGroup()
                        .addComponent(butGenerate)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCoupon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCouponLayout.createSequentialGroup()
                        .addComponent(lblAuthor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWon, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelCouponLayout.setVerticalGroup(
            panelCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCouponLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(panelCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butGenerate)
                    .addComponent(lblCoupon)
                    .addComponent(jLabel5))
                .addGroup(panelCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCouponLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(panelCouponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClose)
                            .addComponent(lblWon, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCouponLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblAuthor)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCoupon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelCoupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
         try {
                 this.dispose();
                  mainFrame.setEnabled(true);
                 mainFrame.requestFocusInWindow();
       }
       catch (RuntimeException ex ){
           
       }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void butGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGenerateActionPerformed
       int ranNum = randInt (1,100);
       lblCoupon.setText(Integer.toString(ranNum));
       
       Coupon co = new Coupon (ranNum);
       int matchNum = co.getMatch();
       
       if (matchNum==2)
       {
           lblWon.setText("You won a 2% coupon !");
       }
      if (matchNum==5)
      {
          lblWon.setText("You won a 5% coupon !");
      }
      if (matchNum==10)
       {
           lblWon.setText("You won a 10% coupon !");
       }
      if (matchNum==15)
      {
          lblWon.setText("You won a 15% coupon !");
      }
      else 
      {
          lblWon.setText("Try again. ");
      }
      
      
      
      
    }//GEN-LAST:event_butGenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton butGenerate;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblCoupon;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblWon;
    private javax.swing.JPanel panelCoupon;
    private javax.swing.JPanel panelDoc;
    private javax.swing.JTextArea tAreaDoc;
    // End of variables declaration//GEN-END:variables


public static int randInt(int min, int max) {

    Random rand = new Random();


    int randomNum = rand.nextInt((max - min) + 1) + min;

    return randomNum;
}











}
