
package UI;
import validation.Formatter;
import logic.*;

/**
 *
 * @author woden_000
 */
public class PriceListUI extends javax.swing.JFrame {
    
    

     CarSaleMainUI mainFrame;
    /**
     * Creates new form TaxSummary
     */
    public PriceListUI (CarSaleMainUI mainFrame){
        initComponents();
        this.mainFrame = mainFrame; 

     
    }
    
    /**
     * Creates new form PriceListUI
     */
    public PriceListUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        butGroupCar = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblOurPrice = new javax.swing.JLabel();
        lblTran = new javax.swing.JLabel();
        lblWheel = new javax.swing.JLabel();
        lblFog = new javax.swing.JLabel();
        lblSeat = new javax.swing.JLabel();
        lblSpeaker = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        butClose = new javax.swing.JButton();
        radButCruze = new javax.swing.JRadioButton();
        radButEquinox = new javax.swing.JRadioButton();
        radButVolt = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMSRP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Price List for 2005 Chevorlate Auto");
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 540));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 0, 153));

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));

        jLabel17.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Price List for 2005 Chevorlate Auto");

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(504, 520));
        jPanel4.setPreferredSize(new java.awt.Dimension(504, 520));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Automate transmission:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 21, 0, 0);
        jPanel4.add(jLabel7, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("17\" 5-spoke painted alumiun:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 21, 0, 0);
        jPanel4.add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Front fog lamps :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 21, 0, 0);
        jPanel4.add(jLabel11, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Power seat:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 21, 0, 0);
        jPanel4.add(jLabel14, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pioneer 6 way speaker:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 21, 0, 0);
        jPanel4.add(jLabel15, gridBagConstraints);

        lblOurPrice.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        lblOurPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblOurPrice.setText("$  00000,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 0);
        jPanel4.add(lblOurPrice, gridBagConstraints);

        lblTran.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        lblTran.setForeground(new java.awt.Color(255, 255, 255));
        lblTran.setText("$  0000,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 23, 0, 0);
        jPanel4.add(lblTran, gridBagConstraints);

        lblWheel.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        lblWheel.setForeground(new java.awt.Color(255, 255, 255));
        lblWheel.setText("$  0000,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 23, 0, 0);
        jPanel4.add(lblWheel, gridBagConstraints);

        lblFog.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        lblFog.setForeground(new java.awt.Color(255, 255, 255));
        lblFog.setText("$  0000,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 23, 0, 0);
        jPanel4.add(lblFog, gridBagConstraints);

        lblSeat.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        lblSeat.setForeground(new java.awt.Color(255, 255, 255));
        lblSeat.setText("$  0000,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 23, 0, 0);
        jPanel4.add(lblSeat, gridBagConstraints);

        lblSpeaker.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        lblSpeaker.setForeground(new java.awt.Color(255, 255, 255));
        lblSpeaker.setText("$  0000,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 23, 0, 0);
        jPanel4.add(lblSpeaker, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 24;
        gridBagConstraints.ipadx = 462;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 21, 0, 21);
        jPanel4.add(jSeparator1, gridBagConstraints);

        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Author: Kevin Chen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 10, 11, 0);
        jPanel4.add(jLabel18, gridBagConstraints);

        butClose.setBackground(new java.awt.Color(0, 153, 204));
        butClose.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        butClose.setText("Close");
        butClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 6, 0, 0);
        jPanel4.add(butClose, gridBagConstraints);

        radButCruze.setBackground(new java.awt.Color(255, 255, 255));
        butGroupCar.add(radButCruze);
        radButCruze.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        radButCruze.setForeground(new java.awt.Color(255, 255, 255));
        radButCruze.setText("Cruze LS");
        radButCruze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radButCruzeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 30, 0, 0);
        jPanel4.add(radButCruze, gridBagConstraints);

        radButEquinox.setBackground(new java.awt.Color(255, 255, 255));
        butGroupCar.add(radButEquinox);
        radButEquinox.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        radButEquinox.setForeground(new java.awt.Color(255, 255, 255));
        radButEquinox.setText("Equinox LS");
        radButEquinox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radButEquinoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 19, 0, 0);
        jPanel4.add(radButEquinox, gridBagConstraints);

        radButVolt.setBackground(new java.awt.Color(255, 255, 255));
        butGroupCar.add(radButVolt);
        radButVolt.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        radButVolt.setForeground(new java.awt.Color(255, 255, 255));
        radButVolt.setText("Volt");
        radButVolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radButVoltActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 32, 0, 0);
        jPanel4.add(radButVolt, gridBagConstraints);

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("Impata");
        jRadioButton4.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 0);
        jPanel4.add(jRadioButton4, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vehicle Price (MSRP):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 21, 0, 0);
        jPanel4.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vehicle Price (Our Price):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 21, 0, 0);
        jPanel4.add(jLabel2, gridBagConstraints);

        lblMSRP.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        lblMSRP.setForeground(new java.awt.Color(255, 255, 255));
        lblMSRP.setText("$  00000,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 10, 0, 0);
        jPanel4.add(lblMSRP, gridBagConstraints);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 540, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCloseActionPerformed
        try {
        this.dispose();
        mainFrame.setEnabled(true);
        mainFrame.requestFocusInWindow();
        }
        catch (RuntimeException ex)
        {
            
        }
    }//GEN-LAST:event_butCloseActionPerformed

    private void radButCruzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radButCruzeActionPerformed
        cruzeInfo();
    }//GEN-LAST:event_radButCruzeActionPerformed

    private void radButEquinoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radButEquinoxActionPerformed
       equinoxInfo();
    }//GEN-LAST:event_radButEquinoxActionPerformed

    private void radButVoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radButVoltActionPerformed
       voltInfo();
    }//GEN-LAST:event_radButVoltActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PriceListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PriceListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PriceListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PriceListUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PriceListUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butClose;
    private javax.swing.ButtonGroup butGroupCar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFog;
    private javax.swing.JLabel lblMSRP;
    private javax.swing.JLabel lblOurPrice;
    private javax.swing.JLabel lblSeat;
    private javax.swing.JLabel lblSpeaker;
    private javax.swing.JLabel lblTran;
    private javax.swing.JLabel lblWheel;
    private javax.swing.JRadioButton radButCruze;
    private javax.swing.JRadioButton radButEquinox;
    private javax.swing.JRadioButton radButVolt;
    // End of variables declaration//GEN-END:variables


public void cruzeInfo (){
    Cruze cr = new Cruze ();
        lblMSRP.setText(Formatter.formatCurrency(cr.getMSRP()));
        lblOurPrice.setText(Formatter.formatCurrency(17500));
        
        lblTran.setText(Formatter.formatCurrency(cr.getTransmission()));
        lblWheel.setText(Formatter.formatCurrency(cr.getWheel()));
        lblFog.setText(Formatter.formatCurrency(cr.getFog()));
        lblSeat.setText(Formatter.formatCurrency(cr.getSeat()));
        lblSpeaker.setText(Formatter.formatCurrency(cr.getSpeaker()));
}


public void equinoxInfo (){
     Equinox eq = new Equinox ();
        lblMSRP.setText(Formatter.formatCurrency(eq.getMSRP()));
        lblOurPrice.setText(Formatter.formatCurrency(21000));
        
        lblTran.setText(Formatter.formatCurrency(eq.getTransmission()));
        lblWheel.setText(Formatter.formatCurrency(eq.getWheel()));
        lblFog.setText(Formatter.formatCurrency(0));
        lblSeat.setText(Formatter.formatCurrency(eq.getSeat()));
        lblSpeaker.setText(Formatter.formatCurrency(eq.getSpeaker()));
    
}


public void voltInfo (){
       Volt vo = new Volt ();
        lblMSRP.setText(Formatter.formatCurrency(vo.getMSRP()));
        lblOurPrice.setText(Formatter.formatCurrency(21000));
        
        lblTran.setText(Formatter.formatCurrency(0));
        lblWheel.setText(Formatter.formatCurrency(vo.getWheel()));
        lblFog.setText(Formatter.formatCurrency(0));
        lblSeat.setText(Formatter.formatCurrency(0));
        lblSpeaker.setText(Formatter.formatCurrency(vo.getSpeaker()));
    
}


}
